"""
User Insights model for storing AI-generated insights and recommendations
"""

from datetime import datetime
from enum import Enum

from sqlalchemy import Column, DateTime, Float, ForeignKey, String, Text
from sqlalchemy.orm import relationship

from app.core.database import Base


class InsightType(str, Enum):
    """Types of insights that can be generated"""

    HABIT_PATTERN = "habit_pattern"
    VOLUME_IMPROVEMENT = "volume_improvement"
    TIMING_OPTIMIZATION = "timing_optimization"
    CONSISTENCY_ANALYSIS = "consistency_analysis"
    STREAK_MOTIVATION = "streak_motivation"
    GOAL_ADJUSTMENT = "goal_adjustment"
    LIQUID_VARIETY = "liquid_variety"
    HEALTH_CORRELATION = "health_correlation"
    WEATHER_ADAPTATION = "weather_adaptation"
    ACTIVITY_HYDRATION = "activity_hydration"


class PriorityLevel(str, Enum):
    """Priority levels for insights"""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class UserInsight(Base):
    """Model for storing user insights generated by AI"""

    __tablename__ = "user_insights"

    id = Column(String, primary_key=True, index=True)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)

    # Insight details
    insight_type = Column(String, nullable=False)  # InsightType enum
    insight_title = Column(String, nullable=False)
    insight_description = Column(Text, nullable=False)

    # Analytics data
    confidence_score = Column(Float, nullable=False, default=0.0)  # 0.0 to 1.0
    priority_level = Column(
        String, nullable=False, default=PriorityLevel.MEDIUM
    )  # PriorityLevel enum

    # Metadata
    data_period_start = Column(DateTime, nullable=True)  # Analysis period start
    data_period_end = Column(DateTime, nullable=True)  # Analysis period end
    insights_data = Column(Text, nullable=True)  # JSON string of raw data used

    # Actions and outcomes
    recommended_action = Column(Text, nullable=True)
    user_acknowledged = Column(
        String, nullable=False, default="pending"
    )  # pending, accepted, dismissed
    user_feedback = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    acknowledged_at = Column(DateTime, nullable=True)
    expires_at = Column(DateTime, nullable=True)  # When insight becomes irrelevant

    # Relationships
    user = relationship("User", back_populates="insights")

    def __repr__(self) -> str:
        return f"<UserInsight(id='{self.id}', type='{self.insight_type}', user='{self.user_id}')>"

    @property
    def is_expired(self) -> bool:
        """Check if insight has expired"""
        if not self.expires_at:
            return False
        return datetime.utcnow() > self.expires_at

    @property
    def priority_score(self) -> int:
        """Get numeric priority score for sorting"""
        priority_scores = {
            PriorityLevel.LOW: 1,
            PriorityLevel.MEDIUM: 2,
            PriorityLevel.HIGH: 3,
            PriorityLevel.URGENT: 4,
        }
        return priority_scores.get(self.priority_level, 2)

    def acknowledge(self, feedback: str = None, accepted: bool = True):
        """Mark insight as acknowledged by user"""
        self.user_acknowledged = "accepted" if accepted else "dismissed"
        self.acknowledged_at = datetime.utcnow()
        if feedback:
            self.user_feedback = feedback

    @classmethod
    def create_insight(
        cls,
        user_id: str,
        insight_type: InsightType,
        title: str,
        description: str,
        confidence: float,
        priority: PriorityLevel = PriorityLevel.MEDIUM,
        action: str = None,
        data_start: datetime = None,
        data_end: datetime = None,
        expires_hours: int = None,
    ) -> "UserInsight":
        """Create a new user insight"""
        insight_id = (
            f"insight_{user_id}_{insight_type}_{int(datetime.utcnow().timestamp())}"
        )

        expires_at = None
        if expires_hours:
            from datetime import timedelta

            expires_at = datetime.utcnow() + timedelta(hours=expires_hours)

        return cls(
            id=insight_id,
            user_id=user_id,
            insight_type=insight_type.value,
            insight_title=title,
            insight_description=description,
            confidence_score=min(max(confidence, 0.0), 1.0),  # Clamp between 0-1
            priority_level=priority.value,
            recommended_action=action,
            data_period_start=data_start,
            data_period_end=data_end,
            expires_at=expires_at,
        )
